### ISSUE TITLE
Requesting arm64 docker image for MacBook M1

### ISSUE THREAD

**Issue by johnapeery** [imunes/vroot-linux#12]
Requesting arm64 docker image for MacBook M1

**Comment by johnapeery** [comment]
Trying to run this with an Ubuntu 22.04 ARM64 VM running on a MacBook Pro w/ the M1.

**Comment by johnapeery** [comment]
'exec docker run' (i55e0.n1) caught:
2c286c38230482a57545eb423bc0d02d0d5868433fa93046d0ac1f6d154b7fd6
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by johnapeery** [comment]
uname -a
Linux ubuntu-linux-22-04-desktop 5.15.0-47-generic #51-Ubuntu SMP Fri Aug 12 08:18:32 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

**Comment by johnapeery** [comment]
processor       : 0
BogoMIPS        : 48.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 asimddp sha512 asimdfhm dit uscat ilrcpc flagm ssbs sb paca pacg dcpodp flagm2 frint
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0x000
CPU revision    : 0

**Comment by johnapeery** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

**Comment by mmikuc** [comment]
Dockerfile for aarch64, based on Ubuntu 20.04, tested on M1:
make arm64
docker tag imunes/template:arm64 imunes/template:latest

**Comment by johnapeery** [comment]
Getting the following:

$ make arm64
make: *** No rule to make target 'arm64'.  Stop.

$ sudo docker pull imunes/template:arm64
Error response from daemon: manifest for imunes/template:arm64 not found: manifest unknown: manifest unknown

$ sudo docker tag imunes/template:arm64 imunes/template:latest
Error response from daemon: No such image: imunes/template:arm64

John Peery

**Comment by mmikuc** [comment]
git pull
make arm64

**Comment by johnapeery** [comment]
$ sudo git pull
Already up to date.

$ sudo make arm64
make: *** No rule to make target 'arm64'.  Stop.

**Comment by johnapeery** [comment]
I've completely removed and re-installed imunes as follows:

$ cd ~
$ sudo apt install openvswitch-switch docker.io xterm wireshark make imagemagick tk tcllib util-linux
$ sudo git clone https://github.com/imunes/imunes.git
$ cd imunes
$ sudo make install
$ sudo imunes -p
$ chmod +s /usr/local/bin/imunes
$ sudo imunes &

I still get the following:

$ sudo docker pull imunes/template:arm64 
Error response from daemon: manifest for imunes/template:arm64 not found: manifest unknown: manifest unknown

$ sudo make arm64
make: *** No rule to make target 'arm64'.  Stop.

**Comment by mmikuc** [comment]
git clone https://github.com/imunes/vroot-linux.git
cd vroot-linux/
sudo make arm64

**Comment by johnapeery** [comment]
$ sudo make arm64
./build.sh arm64
[+] Building 'imunes/template:arm64' from 'arm64'.
The command '/bin/sh -c /build/prepare.sh &&  /build/system_services.sh &&  /build/utilities.sh &&  /build/extras.sh &&  /build/cleanup.sh' returned a non-zero code: 100
make: *** [GNUmakefile:21: arm64] Error 1

**Comment by mmikuc** [comment]
Do you have any partially made docker images?
docker images
docker ps -a

**Comment by johnapeery** [comment]
Cleaning up the stale images worked.

$ sudo make arm64
./build.sh arm64
[+] Building 'imunes/template:arm64' from 'arm64'.
[+] Built image 'imunes/template:arm64' in 56.48676 s.

How do I ensure imunes will use this image when launching the experiment?

**Comment by mmikuc** [comment]
docker tag imunes/template:arm64 imunes/template:latest

**Comment by mmikuc** [comment]
By default, IMUNES uses imunes/template:latest.
In node configuration menu, you can set a different docker image for any host/pc/router ("Docker image")

**Comment by johnapeery** [comment]
Sweet. You’re awesome. That worked.

Thank you so much for all of your help and quick responses. I greatly appreciate you.

**Comment by johnapeery** [comment]
Here are the high-level steps I performed to make this work for anyone else interested:

Setup and install an ARM64 Ubuntu 22.04 Virtual Machine (VM) on your MacBook M1 leveraging your preferred hypervisor (I'm using Parallels Student Edition until VirtualBox supports ARM), then run the following on the Ubuntu VM:

$ cd ~
$ sudo apt install openvswitch-switch docker.io xterm wireshark make imagemagick tk tcllib util-linux
$ git clone https://github.com/imunes/imunes.git
$ cd imunes
$ sudo make install
$ sudo imunes -p
$ sudo chmod u+s /usr/local/bin/imunes
$ git clone https://github.com/imunes/vroot-linux.git
$ cd vroot-linux/
$ sudo make arm64
$ cd ../
$ sudo docker tag imunes/template:arm64 imunes/template:latest
$ sudo imunes &

**Comment by mmikuc** [comment]
Docker image for arm64 (M1) is now on Docker Hub:
sudo imunes -p
